### ISSUE TITLE
scopes

### ISSUE THREAD

**Issue by blake41** [learn-co-curriculum/model-class-methods-reading#2]
Our objectives say create class methods that act like scopes.  I don't know if scopes have been covered before this point but i think it would be good to explain what you mean by this.  like class methods are essentially scopes, they're chainable if you're using the where method and returning a relation etc.

**Comment by blake41** [comment]
@scottcreynolds other than this comment everything looks awesome

**Comment by scottcreynolds** [comment]
@blake41 I'm not sure if the "acts like scopes" part was a directive for me or something intended to be included, to be honest. Do you think it's better to just leave that part out and reword to something like "Create model class methods to support custom queries"? 

Since scopes are nowhere near the object of this lesson I'm wondering if it will just be a distraction.

If not, do you think I should describe it up in the objectives or down as a topic with the actual implementation.

**Comment by blake41** [comment]
@scottcreynolds ahhh got it, nevermind then, i agree with you that it'd be a distraction
