### ISSUE TITLE
Completed but not updating

### ISSUE THREAD

**Issue by malbazaz** [learn-co-curriculum/model-class-methods-reading#9]
I completed the readme but it is not showing that I have completed it.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @malbazaz.

We have updated this lesson to make sure it registers as a lab with tests instead of a readme and believe your issue to have been resolved. However, since you have already forked the older version, in order for learn.co to register this change, you will have to delete your personal fork and revisit the lesson on learn.co to get the updated version. Unfortunately, since this was actually a lab, you'll also have to solve it!
 
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
